# -*- coding: utf-8 -*-
"""
    Plugin constants
"""

THUMBNAIL_HEIGHT_PARAM = 'height'
THUMBNAIL_WIDTH_PARAM = 'width'

THUMBNAIL_HEIGHT = 200
THUMBNAIL_WIDTH = 200

SAS_SUBSCRIPTION_VARIABLE = "PC_SDK_SUBSCRIPTION_KEY"

GDAL_SUBDATASETS_KEY = "SUBDATASETS"
GDAL_METADATA_NAME = "NAME"

STAC_QUERYABLE_TIMESTAMP = "TIMESTAMP"
